// react/src/components/DailyArticle/index.js

import React, { Component } from 'react';
import './index.scss';
import $ from '../../utils/base';
import { getFormatTime } from "../../utils/time";

class DailyArticle extends Component {
  static defaultProps = {
    id: 0
  }
  constructor(props) {
    super(props);
    this.state = {
      data: {},
      comments: []
    }
  }

  // componentDidMount() {
  //   debugger; // todo 监听
  //   this.watch(this.props, function(prop, value) {
  //     if (prop === 'id' && value) {
  //       this.getArticle();
  //       this.getComments();
  //     }
  //   })
  // }
  // @Watch("id")
  // onIdChanged(val) {
  //   if (val) {
  //     this.getArticle();
  //     this.getComments();
  //   }
  // }
  // 监听 props 更改
  componentWillReceiveProps(props) {
    console.log(props.id);
    if (props.id) {
      this.getArticle(props.id);
      this.getComments(props.id);
    }
  }
  // /**
  //  * 监听函数
  //  * @param {*} target 
  //  * @param {*} callback 
  //  */
  // watch(target, callback) {
  //   const proxy = new Proxy(target, {
  //     get: function(target, prop) {
  //       return target[prop];
  //     },
  //     set: function(target, prop, value) {
  //       target[prop] = value;
  //       callback(prop, value)
  //     }
  //   })
  //   return proxy;
  // }
  
  getArticle(id) {
    $.ajax.get("news/" + id).then(
      res => {
        // 将文章中的图片地址替换为代理的地址
        res.body = res.body.replace(/src="http/g, 'src="' + $.imgPath + "http");
        res.body = res.body.replace(
          /src="https/g,
          'src="' + $.imgPath + "https"
        );
        // this.state.data = res;
        this.setState({
          data: res
        })

        // 返回文章顶端
        window.scrollTo(0, 0);
      }
    );
  }
   getComments(id) {
    this.state.comments = [];
    $.ajax.get("story/" + id + "/short-comments").then(
      res => {
        const comments = res.comments.map(
          comment => {
            // 将头像的图片地址转为代理地址
            comment.avatar = $.imgPath + comment.avatar;
            return comment;
          }
        );
        this.setState({
          comments
        })
      }
    );
  }
  render() {
    return (
      <div className="daily-article">
        <div className="daily-article-title">{ this.state.data.title }</div>
        <div className="daily-article-content" dangerouslySetInnerHTML={{__html: this.state.data.body}}>
        {/* { this.state.data.body }; */} 
        </div>
        {
          this.state.comments.length > 0 
            ? <div className="daily-comments">
                <span>评论 {this.state.comments.length }</span>
                {this.state.comments.map(comment => (
                  <div className="daily-comment" key={comment.id}>
                    <div className="daily-comment-avatar">
                      <img src={comment.avatar} alt="" />
                    </div>
                    <div className="daily-comment-content">
                      <div className="daily-comment-name">{ comment.author }</div>
                      <div className="daily-comment-time">
                        { getFormatTime(comment.time) }
                      </div>
                      <div className="daily-comment-text">{ comment.content }</div>
                    </div>
                  </div>
                ))}
              </div>
            : null
        }
      </div>
    )
  }
}

export default DailyArticle;

// src/components/DailyArticle.vue

<template>
  <div class="daily-article">
    <div class="daily-article-title">{{ data.title }}</div>
    <div class="daily-article-content" v-html="data.body"></div>
    <div class="daily-comments" v-show="comments.length">
      <span>评论 {{ comments.length }}</span>
      <div class="daily-comment" v-for="comment in comments" :key="comment.id">
        <div class="daily-comment-avatar">
          <img :src="comment.avatar" alt="" />
        </div>
        <div class="daily-comment-content">
          <div class="daily-comment-name">{{ comment.author }}</div>
          <div class="daily-comment-time" v-time="comment.time">
            {{ comment.time }}
          </div>
          <div class="daily-comment-text">{{ comment.content }}</div>
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts">
import $ from "../libs/util";
import Time from "../directives/time";
// import Vue from "vue";
// import Component from "vue-class-component";
import { Vue, Component, Watch, Prop } from "vue-property-decorator";

@Component({
  name: "DailyArticle",
  directives: { Time }
})
export default class DailyArticle extends Vue {
  private data: Object = {};
  private comments: Array<any> = [];
  @Prop({ default: 0 })
  id: number;

  @Watch("id")
  onIdChanged(val: number) {
    if (val) {
      this.getArticle();
      this.getComments();
    }
  }
  private getArticle(): void {
    $.ajax.get("news/" + this.id).then(
      (res: any): void => {
        // 将文章中的图片地址替换为代理的地址
        res.body = res.body.replace(/src="http/g, 'src="' + $.imgPath + "http");
        res.body = res.body.replace(
          /src="https/g,
          'src="' + $.imgPath + "https"
        );
        this.data = res;

        // 返回文章顶端
        window.scrollTo(0, 0);
      }
    );
  }
  private getComments(): void {
    this.comments = [];
    $.ajax.get("story/" + this.id + "/short-comments").then(
      (res: any): any => {
        this.comments = res.comments.map(
          (comment: any): any => {
            // 将头像的图片地址转为代理地址
            comment.avatar = $.imgPath + comment.avatar;
            return comment;
          }
        );
      }
    );
  }
}
// export default {
//   name: "daily-article",
//   directives: { Time },
//   props: {
//     id: {
//       type: Number,
//       default: 0
//     }
//   },
//   data() {
//     return {
//       data: {},
//       comments: []
//     };
//   },
//   methods: {
//     getArticle(): void {
//       $.ajax.get("news/" + this.id).then(
//         (res: any): void => {
//           // 将文章中的图片地址替换为代理的地址
//           res.body = res.body.replace(
//             /src="http/g,
//             'src="' + $.imgPath + "http"
//           );
//           res.body = res.body.replace(
//             /src="https/g,
//             'src="' + $.imgPath + "https"
//           );
//           this.data = res;

//           // 返回文章顶端
//           window.scrollTo(0, 0);
//         }
//       );
//     },
//     getComments(): void {
//       this.comments = [];
//       $.ajax.get("story/" + this.id + "/short-comments").then(
//         (res: any): any => {
//           this.comments = res.comments.map(
//             (comment: any): any => {
//               // 将头像的图片地址转为代理地址
//               comment.avatar = $.imgPath + comment.avatar;
//               return comment;
//             }
//           );
//         }
//       );
//     }
//   },
//   watch: {
//     id(val) {
//       if (val) {
//         this.getArticle();
//         this.getComments();
//       }
//     }
//   }
// };
</script>
<style>
.daily-arctile {
  margin-left: 450px;
  padding: 20px;
}

.daily-arctile-title {
  padding: 10px 0;
  font-size: 28px;
  font-weight: bold;
  color: hsl(0, 0%, 13%);
}

.view-more a {
  display: block;
  padding: 4px 0;
  border-radius: 3px;

  cursor: pointer;
  background: hsl(210, 25%, 97%);
  color: inherit;
  text-align: center;
  text-decoration: none;
}
</style>
